version: '2.1'

services:
  xlorpaste-backend:
    container_name: xlorpaste
    image: xlorpaste-backend
    build:
      context: .
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    container_name: db
    image: mongo
    expose:
      - 27017
